name 'webconfigcrux'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures webconfigcrux'
long_description 'Installs/Configures webconfigcrux'
version '0.1.0'
